firedrakeproject/Irksome

irksome/getForm.py

Changes use of `bc._original_val` to `bc._original_arg` to keep compatibility with Firedrake #1797

Change to keep up with firedrake master

---

tests/test_inhomogbc.py

This adds a test that fails if the treatment of inhomogeneous boundary conditions is not working.  Note that, at present time, this test fails on Firedrake master, but passes on branch smaclachlan/bc-fix.  See firedrakeproject/firedrake#1806)

Adding test for inhomogeneous BCs

---

setup.py

I broke my firedrake install, then was foiled in running `firedrake-update` because Irksome's `setup.py` tried to `import firedrake` when `python setup.py clean` was called.  With this change, that no longer happens.

Improve idiot-proofing of setup

---

irksome/getForm.py
tests/test_curl.py
tests/test_subdomainbc.py

Boundary conditions defined only on some faces of the boundary were not being read by Irksome as separate faces but rather edges.  Changes were made to getForm.py on how the for loop reads in specifies face id numbers.  A 2d heat test and a 2d curl test are added to validate changes made in getForm.py.

fixing subdomain BCs and adding tests

---

demos/lowlevel/demo_lowlevel_inhomogbc.py.rst
irksome/ButcherTableaux.py
irksome/getForm.py
irksome/stepper.py
tests/test_dirichletbc.py
tests/test_stokes.py

The existing approach to implementing BCs in Irksome is to treat the boundary data as an ODE, implementing `du/dt(x,t) = g'(t)` for a point, x, where a DirichletBC is strongly enforced.
This PR adds functionality to implement the BCs as if they are terms in a DAE, by setting the BCs for the stage values to enforce that the solution reconstruction corresponding each stage should match the BC at the stage time.  For some schemes (LobattoIIIC and RadauIIA, for example), this results is the solution matching the DirichletBC at each timestep.  The theoretical order for this approach matches the stage order of the scheme, while the old approach is limited to (at best) third order.
The old code is preserved, with a switch added in the call to `TimeStepper` or `GetForm` to select between the two …

Implement DAE-style BCs

---

.github/workflows/ci.yml
.gitignore
docs/source/conf.py
irksome/getForm.py
irksome/manipulation.py
irksome/stepper.py
tests/test_time_form_splitting.py

I can cull the type annotations if you like, though I found them somewhat useful when writing the code.
There's a little bit of cleanup here, and then the main thing is `extract_terms` which splits a form into two, a bit with (linear) time-derivatives in it, and the remainder (that must contain no time-derivatives.
@rckirby, @ScottMacLachlan, I think this will be useful for the automated Galerkin-in-time.

Some manipulation on forms containing time derivatives

---

demos/lowlevel/demo_lowlevel_homogbc.py.rst
demos/lowlevel/demo_lowlevel_inhomogbc.py.rst
demos/lowlevel/demo_lowlevel_mixed_heat.py.rst
irksome/getForm.py
irksome/pc.py
irksome/stepper.py
tests/test_stokes.py

This adds functionality for treating certain nullspaces in Irksome, aimed at the case of DAEs, where the nullspace is associated with a constraint.
Given the original product space, we take in an indexed list of subspace indices and nullspace bases, then construct the `MixedVectorSpaceBasis` over the Irksome product space, matching components of that space to this list.  I'm not sure this is the most elegant implementation, but it seems to work.  (I'm open to suggestions here, though!)
I've modified the `test_stokes.py` code to include the nullspace for Stokes in this way, and verified that passing `nullspace=None` in the call to `stepper` produces failing tests (pressure errors are large, but constant, as expected), while including the nullspace produces the desired results.
This would …

Passing nullspace through to treat DAEs like Stokes

---

irksome/manipulation.py
tests/test_time_form_splitting.py

Previously, the facility to split terms with time derivatives from the rest of a form was broken in the case of taking `Dt` of a piece of a mixed function space.  This fixes that and adds a test to check.

Manipulating time derivative forms

---

irksome/getForm.py
irksome/stepper.py

Previously, we pushed the original space's parent onto the big space in RK methods and left it there.  This PR localizes the push/pop operations to the construction and invocation of the NLVS.

move the push/pop of dm

---

tests/test_pc.py

I was not actually using the per field stuff in the `RanaDU` test, so it was using defaults (thankfully it was still passing).

fix test to use the right params

---

irksome/getForm.py
irksome/stage.py

A simple test case using stage type value failed when called with a zero DirichletBC, because we weren't wrapping `bc._original_arg` with `as_ufl`.  This should fix that for all places that we use it.

Wrap up bc args

---

irksome/dirk_stepper.py
irksome/imex.py
irksome/stage.py
irksome/stepper.py
tests/test_dirk.py
tests/test_split.py
tests/test_stokes.py
tests/test_vecbc.py

This addresses the deprecation of `.split()` in UFL raised in Issue #64

.split() -> .subfunctions

---

irksome/stage.py

The changes in #63 seem incomplete, leading to failures for cases where the original function space is a `VectorFunctionSpace`.  This wraps up the single-field objects a little more carefully to not break in this case.

Fix #63 for VFS

---

demos/Makefile

Like the title says, I missed one instance of a hardcoded `pylit` path in #73 . This fixes it.

Missed one hardcoded pylit

---

irksome/ButcherTableaux.py
tests/test_time_form_splitting.py

After https://github.com/firedrakeproject/fiat/pull/49 GLL DOFs inherit the same ordering as Lagrange, which is no longer by coordinate, but now vertex DOFs are ordered first, followed by the interior DOFs. This PR should fix the failing tests.
fixes #76

Ensure DOFs are ordered by coordinate

---

demos/demo_nitsche_heat.py
irksome/dirk_stepper.py
irksome/getForm.py
irksome/imex.py
irksome/stage.py
tests/test_accuracy.py

In #73 , we removed `Constant` for all of our `time` and `dt` objects, by introducing `MeshConstant` in `irksome/tools.py`.  This finishes(?) that job, by removing other places where we assigning constants with domains, and using `MeshConstant` for all of these

Removing Constant domains everywhere I can find them

---

irksome/getForm.py

As written in the Irksome paper, ODE BCs are supposed to set Dirichlet BCs on the stages to match the time derivative of the given Dirichlet BC on the solution.  This was unintentionally changed in #24, when we combined code between ODE and DAE BCs.
This PR fixes the constants introduced in #24 to be zero, so that we restore the original behaviour.

Fix ODE BCs

---

tests/test_odevsdae.py

We should have added this with the previous PR fixing the BC.  But there you have it.

Add test for ODE/DAE with incompatible BC

---

tests/test_split.py

What the title says.  This one test is of a feature we're not actively developing, unsure of, plan to do future work, and keep having to deal with asynchronous solver failures of.

skip the pernicious split NSE test

---

irksome/tools.py

The current counting of nullspace components assumes that there's a null space associated with the last space in a mixed space.  That's dumb, and this fixes it.

Fix nullspace bug

---

.github/workflows/ci.yml

This is in preparation for the rollout of Mac build runners.

Specify that build runners run Linux

---

irksome/__init__.py
irksome/pc.py
tests/test_pc.py

It does what it says.  Tested by preconditioning reaction/diffusion with just diffusion as a simple example.

Add new PC based on providing an alternate time-dependent PDE

---

demos/lowlevel/demo_lowlevel_homogbc.py.rst
demos/lowlevel/demo_lowlevel_inhomogbc.py.rst
demos/lowlevel/demo_lowlevel_mixed_heat.py.rst
irksome/bcs.py
irksome/getForm.py
irksome/imex.py
irksome/pc.py
irksome/stage.py
irksome/stepper.py
irksome/tools.py
tests/test_split.py
tests/test_stokes.py

To allow `DirichletBC(V, 0, ...) `, the special case requires no computation for stage boundary condition, everything should be zero

Fix boundary conditions

---

irksome/explicit_stepper.py

If one passed `solver_parameters=None` into an explicit stepper, it's rewriting the Jacobian/PC options should fail.  This converts the `None` into an empty dictionary.

fix solver options for explicit solver

---

irksome/dirk_stepper.py
irksome/explicit_stepper.py
tests/test_explicit.py

When BCs were refactored in #98, the DIRK case was left untouched.
This PR aims to correct that, as well as addressing the root problem in #102, where we don't implement the correct DAE-style BCs for explicit schemes
fixes #102

Fix DIRK boundary conditions

---

irksome/discontinuous_galerkin_stepper.py
irksome/galerkin_stepper.py
irksome/imex.py
irksome/stage.py

Some attempts to optimize by introducing tensor-valued `Constants`

Fix Constants

---

demos/monodomain/demo_monodomain_FHN.py.rst
demos/monodomain/demo_monodomain_FHN_dirkimex.py.rst
docs/source/index.rst
irksome/__init__.py
irksome/dirk_imex_tableaux.py
irksome/imex.py
irksome/stepper.py
tests/test_imex.py

This adds an implementation of the DIRK-IMEX method from the Ascher-Ruuth-Spiteri 1997 Applied Numerical Mathematics paper.  Mostly this layers the IMEX part on top of the existing DIRK code (but is different enough that reuse is not feasible).

Add DIRK-IMEX schemes

---

irksome/imex.py
tests/test_dirk.py
tests/test_imex.py

This attempts to fix #109 in one of the two possible ways.  Includes a test that fails without the fix.

DIRK-IMEX and VFS

---

.github/workflows/docs.yml

We're seeing unrelated failures in the doc build in #112, that are difficult to debug since that's from a fork.  Trying to fix these here, for efficiency.

Fix doc build

---

irksome/deriv.py
irksome/dirk_stepper.py
irksome/discontinuous_galerkin_stepper.py
irksome/galerkin_stepper.py
irksome/getForm.py
irksome/imex.py
irksome/stage.py
irksome/tools.py
tests/test_dirk.py

Executive summary:
- `component_replace` takes a dictionary of replacements and programmatically inserts replacements of all sub-components.  This was a commonly used pattern, so tucking it into a function simplifies things.
- it is also easier to iterate over scalar components of a ufl `Function` or `TestFunction` by indexing, so we don't have to use `split` and then worry whether the pieces were scalar or vector-valued.  This is largely hidden inside `component_replace`
- `TimeDerivative` now pushes through tensors during construction, and this greatly simplified some of the replacements.
These key changes required pervasive simplification of all of our the UFL manipulation in our various time steppers.
We explored `Constant` around numpy versus numpy array of `Constant` objects.  The …

Refactor replacements

---

irksome/__init__.py
irksome/deriv.py
irksome/dirk_stepper.py
irksome/discontinuous_galerkin_stepper.py
irksome/galerkin_stepper.py
irksome/imex.py
irksome/stage_derivative.py
irksome/stage_value.py
irksome/tools.py
tests/test_accuracy.py
tests/test_bern.py
tests/test_curl.py
tests/test_differentiation.py
tests/test_dirk.py
tests/test_disc_galerkin.py
tests/test_galerkin.py
tests/test_imex.py

This PR adds support for `Dt(expr(t), order)` where `expr(t)` can be a general time-dependent UFL expression, and `order` >= 0 can be arbitrary.

Enhacements for TimeDerivative

---

irksome/deriv.py
irksome/dirk_stepper.py
irksome/discontinuous_galerkin_stepper.py
irksome/galerkin_stepper.py
irksome/imex.py
irksome/nystrom_stepper.py
irksome/stage_derivative.py
irksome/stage_value.py
irksome/tools.py

This PR changes the preprocessing of `TimeDerivative` so that `Dt` gets pushed inside `Indexed`, ie. `Dt(u[i]) -> Dt(u)[i]`. This means that ultimately we only need to do replacements on `Dt(u)`, as opposed to separate replacements for each individual component `Dt(u[i])`.

Clean up UFL manipulation

---

demos/nystrom/demo_wave_explicit.py.rst
docs/source/index.rst
irksome/nystrom_stepper.py
tests/test_nystrom.py

When using Nystrom with an explicit Tableau, the "natural" way to do DAE BCs is to impose them based on the stage approximations of du/dt, not of u.  This introduces code to do this, in both the explicit and implicit cases.

Add dDAE BCs for Nystrom

---

irksome/deriv.py
tests/test_differentiation.py

This should extend support to time-dependent `Forms` involving generic `BaseForms` (`Cofunctions`, `ExternalOperators`, etc). Initially these generic terms are treated as time independent.

TimeDerivativeRuleDispatcher: handle generic UFL types

---

irksome/stage_derivative.py
tests/test_equationbc.py

In PR https://github.com/firedrakeproject/Irksome/pull/138 we missed the fact that EquationBCs can own BCs of their own, and these must also be accounted for. This is important when using EquationBCs and DirichletBCs at the same time on different parts of the boundary. This pull request incorporates that.

Correctly incorporate BCs that are passed to EquationBC

---

irksome/base_time_stepper.py
irksome/dirk_stepper.py
irksome/discontinuous_galerkin_stepper.py
irksome/explicit_stepper.py
irksome/galerkin_stepper.py
irksome/imex.py
irksome/nystrom_stepper.py
irksome/pc.py
irksome/stage_derivative.py
irksome/stage_value.py
tests/test_nystrom_pc.py
tests/test_pc.py

This lets us streamline a lot of business in preconditioners that re-discretize in time.
As a further simplification, we could remove everything that's in the appctx that is also a member of the class.  Not sure that wouldn't upset anybody?

steppers go into appctx

---

irksome/deriv.py

This PR has to be merged as soon as (but not before) `ufl.DAGTraversal` lands in UFL `release`.

Implement TimeDerivativeRuleset as a DAGTraverser

---

irksome/nystrom_stepper.py

There's a typo in our Classic Nystrom Tableau, in comparison to that given in Hairer-Norsett-Wanner (see attached screenshot).  Let's maybe fix that...

Fix Tableau typo

---

irksome/stepper.py

When an invalid kwarg is passed to `TimeStepper`, we catch it and error out, but don't provide a useful message about which kwarg is invalid.  This fixes that oversight.

Useful error message

---

tests/test_curl.py

We were getting warnings because one of our tests still used the future interpolate.

fix interpolate import to be up-to-date with Firedrake.
